version: '3.8'
services:
  postgres-challenge:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_challenge
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init_db_challenge.sql
    ports:
      - "5433:5432"

  nttdata-msa-person-client:
    build:
      context: ./nttdata-msa-person-client
      dockerfile: Dockerfile
    container_name: nttdata-msa-person-client
    ports:
      - "8080:8080"
    depends_on:
      - postgres-challenge
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgres://postgres-challenge:5432/db_challenge
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password

  nttdata-msa-account-transaction:
    build:
      context: ./nttdata-msa-account-transaction
      dockerfile: Dockerfile
    container_name: nttdata-msa-account-transaction
    ports:
      - "8081:8081"
    depends_on:
      - postgres-challenge
      - nttdata-msa-person-client
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgres://postgres-challenge:5432/db_challenge
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      CLIENT_SERVICE_URL: http://nttdata-msa-person-client:8080
